apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregator
  namespace: news-aggregator-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-aggregator
  template:
    metadata:
      labels:
        app: news-aggregator
    spec:
      serviceAccountName: news-aggregator-sa
      containers:
        - name: news-aggregator
          image: ayeremenko/news-aggregator:1.0.0 # Need be updated to the latest version
          ports:
            - containerPort: 8443
          volumeMounts:
            - mountPath: "/resources" # This directory used to store all fetched resources.
              name: news-aggregator-resources-storage
            - mountPath: "/config" # This directory stores a configuration file, with the list of all registered feeds.
              name: news-aggregator-config-storage
      volumes:
        - name: news-aggregator-resources-storage
          persistentVolumeClaim:
            claimName: news-aggregator-resources-pvc
        - name: news-aggregator-config-storage
          persistentVolumeClaim:
            claimName: news-aggregator-config-pvc