apiVersion: v2
name: news-aggregator-server
description: a chart that deploys a news aggregator https server
type: application
version: 1.0.0
appVersion: "2.0"

dependencies:
  - name: cert-manager
    version: 1.15.3
    repository: https://charts.jetstack.io

maintainers:
  - name: Andrii Yeremenko
    email: andrii.yeremenko@teamdev.com