apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: news-aggregator
  namespace: argocd
spec:
  description: "A versatile tool for aggregating news from various sources"
  sourceRepos:
    - https://github.com/andrii-yeremenko/news-aggregator.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'