version: '3'

env:
  SERVER_PATH: "./cmd/web_server/main"
  CLI_PATH: "./cmd/cli/main"
  DOCKER_IMAGE_NAME: "ayeremenko/news-aggregator"
  DOCKERFILE_PATH: "Dockerfile"
  SERVER_EXPOSE_PORT: "8443"
  DOCKER_RUN_PORT: "443"
  DOCKER_TAG: "1.0.0"
  LINT_VERSION: "v1.42.1"
  GO_VERSION: "1.21"
  BIN_PATH: "./bin"

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  web_server:
    taskfile: ./cmd/web_server/Taskfile.yml
  cli:
    taskfile: ./cmd/cli/Taskfile.yml

tasks:
  tidy:
    desc: "Tidies the Go module dependencies"
    cmd: |
      go mod tidy

  test:
    desc: "Run all tests"
    cmd: |
      go test ./...

  fmt:
    desc: "Run go fmt on all Go files"
    cmd: |
      go fmt ./...

  vet:
    desc: "Run go vet on all Go files"
    cmd: |
      go vet ./...

  lint:
    desc: "Run golangci-lint"
    cmd: |
      golangci-lint run

  lint-all:
    desc: "Run all linters"
    deps:
      - fmt
      - vet
      - lint

  build-web-server:
    desc: "Build the web_server"
    deps:
      - tidy
      - test
    cmd: |
      task web_server:build

  build-cli:
    desc: "Build the CLI"
    deps:
      - tidy
      - test
    cmd: |
      task cli:build

  build-all:
    desc: "Build all binaries"
    deps:
      - tidy
      - test
    cmds:
      - task web_server:build
      - task cli:build

  docker-build:
    desc: "Build the Docker image for web_server"
    silent: true
    deps:
      - test
    cmd: |
      docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG -f $DOCKERFILE_PATH .

  docker-run:
    desc: "Run the web_server Docker container"
    deps:
      - docker-build
    cmd: |
      docker run -p $DOCKER_RUN_PORT:$SERVER_EXPOSE_PORT $DOCKER_IMAGE_NAME

  docker-push:
    desc: "Push the Docker image to the registry"
    deps:
      - docker-build
    cmd: |
      docker push ayeremenko/news-aggregator:$DOCKER_TAG

  cli-run:
    desc: "Run the CLI locally"
    deps:
      - build-cli
    cmd: |
      task cli:run

  server-run:
    desc: "Run the web server locally"
    deps:
      - build-web-server
    cmd: |
      task web_server:run

  clean:
    desc: "Clean build artifacts"
    deps:
      - web_server:clean
      - cli:clean