version: '3'

env:
  SERVER_PATH: "./cmd/web_server/main"
  CLI_PATH: "./cmd/cli/main"
  DOCKER_IMAGE_NAME: "ayeremenko/news-aggregator"
  DOCKERFILE_PATH: "Dockerfile"
  SERVER_EXPOSE_PORT: "8443"
  DOCKER_RUN_PORT: "443"
  DOCKER_TAG: "2.0.0"
  K8S_TEMPLATES_PATH: "./templates"
  LOCAL_PORT: "8888"
  SERVICE_PORT: "443"

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

includes:
  web_server:
    taskfile: ./cmd/web_server/Taskfile.yml
  cli:
    taskfile: ./cmd/cli/Taskfile.yml

tasks:
  download:
    desc: "Download all dependencies"
    cmd: |
      go mod download

  tidy:
    desc: "Tidies the Go module dependencies"
    cmd: |
      go mod tidy

  generate:
    desc: Generate all mocks
    cmds:
      - go install github.com/golang/mock/mockgen@v1.6.0
      - go generate ./...

  test:
    desc: "Run all tests"
    deps:
      - generate
    cmd: |
      go test ./...

  fmt:
    desc: "Run go fmt on all Go files"
    cmd: |
      go fmt ./...

  vet:
    desc: "Run go vet on all Go files"
    cmd: |
      go vet ./...

  lint:
    desc: "Run golangci-lint"
    cmd: |
      golangci-lint run

  run-quality-checks:
    desc: "Run all quality checks"
    deps:
      - fmt
      - vet
      - lint

  build-all:
    desc: "Build all binaries"
    cmds:
      - task web_server:build
      - task cli:build

  docker-build:
    desc: "Build the Docker image for web_server"
    silent: true
    deps:
      - test
    cmd: |
      docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG -f $DOCKERFILE_PATH .

  docker-run:
    desc: "Run the web_server Docker container"
    deps:
      - docker-build
    cmd: |
      docker run -p $DOCKER_RUN_PORT:$SERVER_EXPOSE_PORT $DOCKER_IMAGE_NAME

  docker-push:
    desc: "Push the Docker image to the registry"
    deps:
      - docker-build
    cmd: |
      docker push ayeremenko/news-aggregator:$DOCKER_TAG

  clean:
    desc: Clean build artifacts and remove all 'mocks' directories
    cmds:
      - task web_server:clean
      - task cli:clean
      - find . -type d -name mocks -exec rm -rf {} +

  create-namespace:
    desc: "Create a namespace for the news-aggregator app"
    cmds:
      - kubectl apply -f $K8S_TEMPLATES_PATH/namespace
      - echo "Namespace created"

  delete-namespace:
    desc: "Delete the namespace for the news-aggregator app"
    cmds:
      - kubectl delete -f $K8S_TEMPLATES_PATH/namespace
      - echo "Namespace deleted"

  create-volumes:
    desc: "Create a PersistentVolume and PersistentVolumeClaim"
    deps:
      - create-namespace
    cmds:
      - kubectl apply -f $K8S_TEMPLATES_PATH/volume
      - echo "Volumes created"

  delete-volumes:
    desc: "Delete the PersistentVolume and PersistentVolumeClaim"
    cmds:
      - kubectl delete -f $K8S_TEMPLATES_PATH/volume
      - echo "Volumes deleted"

  deploy:
    desc: "Deploy the news-aggregator app on the Kubernetes cluster"
    deps:
      - create-namespace
    cmds:
      - kubectl apply -f $K8S_TEMPLATES_PATH/app
      - kubectl apply -f $K8S_TEMPLATES_PATH/rbac
      - kubectl apply -f $K8S_TEMPLATES_PATH/cronjob
      - echo "The news-aggregator app has been deployed"

  undeploy:
    desc: "Remove the news-aggregator app from the Kubernetes cluster"
    cmds:
      - kubectl delete -f $K8S_TEMPLATES_PATH/app -n news-aggregator-namespace
      - kubectl delete -f $K8S_TEMPLATES_PATH/rbac -n news-aggregator-namespace
      - kubectl delete -f $K8S_TEMPLATES_PATH/cronjob -n news-aggregator-namespace
      - echo "The news-aggregator app has been removed from the Kubernetes cluster"

  port-forward:
    desc: "Port-forward to access the news-aggregator app"
    cmds:
      - kubectl port-forward service/news-aggregator $LOCAL_PORT:$SERVICE_PORT -n news-aggregator-namespace > port-forward.log 2>&1 &
      - echo "Port forwarding started on localhost:$LOCAL_PORT. Check port-forward.log for details."

  port-remove:
    desc: "Stop port-forwarding for the news-aggregator app"
    cmds:
      - pkill -f 'kubectl port-forward'
      - rm port-forward.log
      - echo "Stopped port-forwarding."

  setup-feeds:
    desc: "Setup the news feeds"
    cmds:
      - |
        if ! kubectl get crd feeds.news-aggregator.com.teamdev >/dev/null 2>&1; then
          echo "Error: Feed CRD is not installed. Cannot proceed with feed setup."
          exit 1
        else
          echo "Feed CRD is installed."
        fi
      - |
        if ! kubectl get deployment operator-controller-manager -n operator-system >/dev/null 2>&1; then
          echo "Error: Operator Feed operator is not installed. Cannot proceed with feed setup."
          exit 1
        else
          echo "Operator is installed."
        fi
      - kubectl apply -f $K8S_TEMPLATES_PATH/feed
      - echo "Feeds setup"

  teardown-feeds:
    desc: "Delete the news feeds"
    cmds:
      - kubectl delete -f $K8S_TEMPLATES_PATH/feed
      - echo "Feeds deleted"

  add-hotnews:
    desc: "Add a new HotNews object"
    cmds:
      - kubectl apply -f $K8S_TEMPLATES_PATH/hotnews
      - echo "HotNews object added"

  remove-hotnews:
    desc: "Remove the HotNews object"
    cmds:
      - kubectl delete -f $K8S_TEMPLATES_PATH/hotnews
      - echo "HotNews object removed"

  configure-feeds-map:
    desc: "Configure the feeds map"
    cmds:
      - kubectl apply -f $K8S_TEMPLATES_PATH/configmap/feeds-group.yaml
      - echo "Feeds map configured"

  unconfigure-feeds-map:
    desc: "Unconfigure the feeds map"
    cmds:
      - kubectl delete -f $K8S_TEMPLATES_PATH/configmap/feeds-group.yaml
      - echo "Feeds map unconfigured"
