version: '3'

env:
  OPERATOR_IMAGE_NAME: "news-updater"
  OPERATOR_DOCKERFILE_PATH: "Dockerfile"
  OPERATOR_TAG: "1.0.0"
  AWS_ACCOUNT_ID: "406477933661"
  AWS_REGION: "us-east-1"

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:

  aws-auth-docker:
    desc: "Authenticate Docker with AWS ECR"
    cmds:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  download:
    desc: "Download all dependencies"
    cmd: |
      go mod download

  tidy:
    desc: "Tidies the Go module dependencies"
    cmd: |
      go mod tidy

  generate:
    desc: Generate all mocks
    cmds:
      - go install github.com/golang/mock/mockgen@v1.6.0
      - go generate ./...

  test:
    desc: "Run all tests"
    deps:
      - generate
    cmd: |
      go test ./...

  fmt:
    desc: "Run go fmt on all Go files"
    cmd: |
      go fmt ./...

  build:
    desc: "Build the updater"
    cmd: |
      go build -o news-updater main.go
  run:
    desc: "Run the updater"
    cmd: |
      go run main.go    

  updater-build:
    desc: "Build the Docker image"
    cmd: |
      docker build -t $OPERATOR_IMAGE_NAME:$OPERATOR_TAG -f $OPERATOR_DOCKERFILE_PATH .

  updater-push-aws:
    desc: "Push the Docker image to AWS ECR"
    deps:
      - aws-auth-docker
      - updater-build
    cmd: |
      aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      docker tag $OPERATOR_IMAGE_NAME:$OPERATOR_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$OPERATOR_IMAGE_NAME:$OPERATOR_TAG
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$OPERATOR_IMAGE_NAME:$OPERATOR_TAG