apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-aggregator-day0
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: news-aggregator
  source:
    repoURL: 'https://github.com/andrii-yeremenko/news-aggregator.git'
    targetRevision: ci-cd/gitops
    path: 'news-aggregator-day0'
    helm:
      parameters:
        - name: accessKey
          value: ""
        - name: secretKey
          value: ""
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: news-aggregator-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: newsaggregator-regcred
      namespace: news-aggregator-namespace
      jsonPointers:
        - "/data"