---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-service-account
  namespace: news-aggregator-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: news-aggregator-namespace
  name: role-full-access-to-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["regcred"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: health-check-role-binding
  namespace: news-aggregator-namespace
subjects:
  - kind: ServiceAccount
    name: aws-service-account
    namespace: news-aggregator-namespace
    apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""