apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ecrConfigName }}
  namespace: {{ .Values.namespace }}
data:
  AWS_REGION: "{{ .Values.region }}"
  DOCKER_SECRET_NAME: "{{ .Values.pullSecretName }}"