apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ecrSecretName }}
  namespace: {{ .Values.namespace }}
stringData:
  AWS_SECRET_ACCESS_KEY: "{{ .Values.secretKey }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.accessKey }}"
  AWS_ACCOUNT: "{{ .Values.account }}"