apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ecrSecretName }}
  namespace: {{ .Values.namespace }}
stringData:
  AWS_SECRET_ACCESS_KEY: "{{ required "The secretKey is required and must be provided" .Values.secretKey }}"
  AWS_ACCESS_KEY_ID: "{{ required "The accessKey is required and must be provided" .Values.accessKey }}"
  AWS_ACCOUNT: "{{ required "The account is required and must be provided" .Values.account }}"