apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-aggregator-resources-pvc
  namespace: news-aggregator-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi