apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: news-aggregator-role
  namespace: news-aggregator-namespace
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]