apiVersion: v1
kind: Service
metadata:
  name: news-aggregator
  namespace: news-aggregator-namespace
spec:
  type: ClusterIP
  selector:
    app: news-aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443