apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: news-aggregator-tls
  namespace: {{ .Values.namespace.name }}
spec:
  secretName: news-aggregator-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: news-aggregator
  dnsNames: