apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaims.config.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaims.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaims.config.storage }}