apiVersion: v1
kind: PersistentVolume
metadata:
  name: { { .Values.persistentVolumes.resources.name } }
  namespace: { { .Values.namespace.name } }
spec:
  capacity:
    storage: { { .Values.persistentVolumes.resources.storage } }
  accessModes:
    - { { .Values.persistentVolumes.resources.accessMode } }
  hostPath:
    path: { { .Values.persistentVolumes.resources.hostPath } }