apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: { { .Values.rbac.roleBinding.name } }
  namespace: { { .Values.namespace.name } }
subjects:
  - kind: ServiceAccount
    name: { { .Values.serviceAccountName } }
    namespace: { { .Release.Namespace } }
roleRef:
  kind: Role
  name: { { .Values.rbac.role.name } }
  apiGroup: rbac.authorization.k8s.io