apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
  namespace: {{ .Values.namespace.name }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: news-updater
              image: {{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}
              volumeMounts:
                  - name: config-volume
                    mountPath: /config
                  - name: resources-volume
                    mountPath: /resources
          restartPolicy: OnFailure
          volumes:
            - name: config-volume
              persistentVolumeClaim:
                claimName: {{ .Values.configStorage.persistentVolumeClaim }}
            - name: resources-volume
              persistentVolumeClaim:
                claimName: {{ .Values.resourcesStorage.persistentVolumeClaim }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}