{{- if .Values.vpa.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-vpa
  namespace: {{ .Values.namespace.name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       {{ .Release.Name }}-deployment
  updatePolicy:
    updateMode: "{{ .Values.vpa.updateMode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Release.Name }}-deployment
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu }}
          memory: {{ .Values.vpa.minAllowed.memory  }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu }}
          memory: {{ .Values.vpa.maxAllowed.memory }}
        controlledValues: RequestsAndLimits
{{- end }}