apiVersion: v1
kind: PersistentVolume
metadata:
  name: news-aggregator-config-pv
  namespace: news-aggregator-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/news-aggregator/config"