---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-service-account
  namespace: operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: operator-system
  name: role-create-secrets-only
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: health-check-role-binding
  namespace: operator-system
subjects:
  - kind: ServiceAccount
    name: aws-service-account
    namespace: operator-system
    apiGroup: ""
roleRef:
  kind: Role
  name: role-create-secrets-only
  apiGroup: ""
