apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aws-secret.yaml
- aws-config.yaml
- aws-service-account.yaml
- aws-update-cronjob.yaml

secretGenerator:
  - name: ecr-registry-helper-secrets
    envs:
      - aws-credentials.env
    behavior: merge
    namespace: operator-system
generatorOptions:
  disableNameSuffixHash: true