name: Push to ECR

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.event.pull_request.number }}-Push to ECR
  cancel-in-progress: false

jobs:
  run:
    name: Push to ECR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Verify Go installation
        run: go version

      - name: Install Task
        run: |
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install dependencies
        run: task download

      - name: Tidy Go module dependencies
        run: task tidy

      - name: Format Go files
        run: task fmt

      - name: Check for unformatted files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Unformatted files detected. Please run 'task fmt' and commit the changes.";
            git diff;
            exit 1;
          fi

      - name: Authenticate AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Push Helm chart to ECR
        run: |
          task pushChart

      - name: Push HTTPS server to ECR
        run: |
          task docker-push-aws

      - name: Push Cron job to ECR
        run: |
          cd updater
          task docker-push-aws
          cd ..

      - name: Push Operator to ECR
        run: |
          cd operator
          task docker-push-aws
          cd ..